kind: ServiceAccount
apiVersion: v1
metadata:
  name: {{ template "fullname" . }}
---
kind: ClusterRole
{{- if semverCompare "^1.8-0" .Capabilities.KubeVersion.GitVersion }}
apiVersion: rbac.authorization.k8s.io/v1
{{- else }}
apiVersion: rbac.authorization.k8s.io/v1beta1
{{- end }}
metadata:
  name: {{ template "fullname" . }}
rules:
  - apiGroups:
      - ""
    resources:
      - nodes/stats
    verbs:
      - get
---
kind: ClusterRoleBinding
{{- if semverCompare "^1.8-0" .Capabilities.KubeVersion.GitVersion }}
apiVersion: rbac.authorization.k8s.io/v1
{{- else }}
apiVersion: rbac.authorization.k8s.io/v1beta1
{{- end }}
metadata:
  name: {{ template "fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ template "fullname" . }}
  namespace: {{ .Release.Namespace }}
- kind: User
  name: system:serviceaccount:monitoring:default
