name: influxdb
version: 1.7.4
description: Scalable datastore for metrics, events, and real-time analytics.
keywords:
- influxdb
- database
- timeseries
home: https://www.influxdata.com/time-series-platform/influxdb/
sources:
  - https://github.com/influxdata/influxdb
maintainers:
- name: 
  email:
engine: gotpl
